
[package]
name = "ra6m2"
version = "0.3.0"
edition = "2024"
description = "Peripheral Access Crate (PAC) for R7FA6M2."
authors = ["Nathan Larsen <n8tlarsen@gmail.com>", "Addison Heavner <addisonheavner@gmail.com>", "Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra6m2", "ra", "arm", "cortex-m", "renesas"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ra-rs/ra"
documentation = "https://docs.rs/crate/ra6m2-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
readme = "README.md"

[package.metadata.docs.rs]
features = ["all-peripherals", "critical-section", "rt"]

[dependencies]
critical-section = { version = "1.1", optional = true }
cortex-m = "0.7"
cortex-m-rt = { version = "0.7.5", optional = true }
vcell = "0.1.3"
portable-atomic = { version = "1.11.0"}

[features]

rt = ["cortex-m-rt/device"]
critical-section = ["dep:critical-section"]

acmphs0 = []
acmphs1 = []
acmphs2 = []
acmphs3 = []
acmphs4 = []
acmphs5 = []
adc120 = []
adc121 = []
agt0 = []
agt1 = []
ami = []
bus = []
cac = []
can0 = []
can1 = []
crc = []
ctsu = []
dac12 = []
dbg = []
dma = []
dmac0 = []
dmac1 = []
dmac2 = []
dmac3 = []
dmac4 = []
dmac5 = []
dmac6 = []
dmac7 = []
doc = []
dtc = []
edmac0 = []
elc = []
etherc0 = []
fcache = []
gpt3210 = []
gpt3211 = []
gpt3212 = []
gpt3213 = []
gpt328 = []
gpt329 = []
gpt32e4 = []
gpt32e5 = []
gpt32e6 = []
gpt32e7 = []
gpt32eh0 = []
gpt32eh1 = []
gpt32eh2 = []
gpt32eh3 = []
gpt_odc = []
gpt_ops = []
icu = []
iic0 = []
iic1 = []
iic2 = []
irda = []
iwdt = []
kint = []
mmf = []
mmpu = []
mstp = []
pdc = []
pfs = []
pmisc = []
poeg = []
port0 = []
port1 = []
port2 = []
port3 = []
port4 = []
port5 = []
port6 = []
port7 = []
port8 = []
port9 = []
porta = []
portb = []
qspi = []
rtc = []
sci0 = []
sci1 = []
sci2 = []
sci3 = []
sci4 = []
sci5 = []
sci6 = []
sci7 = []
sci8 = []
sci9 = []
sdhi0 = []
sdhi1 = []
smpu = []
spi0 = []
spi1 = []
spmon = []
sram = []
src = []
srcram = []
ssie0 = []
ssie1 = []
system = []
tsn = []
usbfs = []
usbhs = []
wdt = []
all-peripherals = ["acmphs0", "acmphs1", "acmphs2", "acmphs3", "acmphs4", "acmphs5", "adc120", "adc121", "agt0", "agt1", "ami", "bus", "cac", "can0", "can1", "crc", "ctsu", "dac12", "dbg", "dma", "dmac0", "dmac1", "dmac2", "dmac3", "dmac4", "dmac5", "dmac6", "dmac7", "doc", "dtc", "edmac0", "elc", "etherc0", "fcache", "gpt3210", "gpt3211", "gpt3212", "gpt3213", "gpt328", "gpt329", "gpt32e4", "gpt32e5", "gpt32e6", "gpt32e7", "gpt32eh0", "gpt32eh1", "gpt32eh2", "gpt32eh3", "gpt_odc", "gpt_ops", "icu", "iic0", "iic1", "iic2", "irda", "iwdt", "kint", "mmf", "mmpu", "mstp", "pdc", "pfs", "pmisc", "poeg", "port0", "port1", "port2", "port3", "port4", "port5", "port6", "port7", "port8", "port9", "porta", "portb", "qspi", "rtc", "sci0", "sci1", "sci2", "sci3", "sci4", "sci5", "sci6", "sci7", "sci8", "sci9", "sdhi0", "sdhi1", "smpu", "spi0", "spi1", "spmon", "sram", "src", "srcram", "ssie0", "ssie1", "system", "tsn", "usbfs", "usbhs", "wdt"]
