#[doc = "Register `GTADSMR` reader"]
pub struct R(crate::R<GTADSMR_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<GTADSMR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<GTADSMR_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<GTADSMR_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `GTADSMR` writer"]
pub struct W(crate::W<GTADSMR_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<GTADSMR_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<GTADSMR_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<GTADSMR_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `ADSMS0` reader - A/D Conversion Start Request Signal Monitor 0 Selection"]
pub type ADSMS0_R = crate::FieldReader<u8, ADSMS0_A>;
#[doc = "A/D Conversion Start Request Signal Monitor 0 Selection\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum ADSMS0_A {
    #[doc = "0: A/D conversion start request signal generated by the GTADTRA register during up-counting."]
    _00 = 0,
    #[doc = "1: A/D conversion start request signal generated by the GTADTRA register during down-counting."]
    _01 = 1,
    #[doc = "2: A/D conversion start request signal generated by the GTADTRB register during up-counting."]
    _10 = 2,
    #[doc = "3: A/D conversion start request signal generated by the GTADTRB register during down-counting."]
    _11 = 3,
}
impl From<ADSMS0_A> for u8 {
    #[inline(always)]
    fn from(variant: ADSMS0_A) -> Self {
        variant as _
    }
}
impl ADSMS0_R {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub fn variant(&self) -> ADSMS0_A {
        match self.bits {
            0 => ADSMS0_A::_00,
            1 => ADSMS0_A::_01,
            2 => ADSMS0_A::_10,
            3 => ADSMS0_A::_11,
            _ => unreachable!(),
        }
    }
    #[doc = "Checks if the value of the field is `_00`"]
    #[inline(always)]
    pub fn is_00(&self) -> bool {
        *self == ADSMS0_A::_00
    }
    #[doc = "Checks if the value of the field is `_01`"]
    #[inline(always)]
    pub fn is_01(&self) -> bool {
        *self == ADSMS0_A::_01
    }
    #[doc = "Checks if the value of the field is `_10`"]
    #[inline(always)]
    pub fn is_10(&self) -> bool {
        *self == ADSMS0_A::_10
    }
    #[doc = "Checks if the value of the field is `_11`"]
    #[inline(always)]
    pub fn is_11(&self) -> bool {
        *self == ADSMS0_A::_11
    }
}
#[doc = "Field `ADSMS0` writer - A/D Conversion Start Request Signal Monitor 0 Selection"]
pub type ADSMS0_W<'a, const O: u8> =
    crate::FieldWriterSafe<'a, u32, GTADSMR_SPEC, u8, ADSMS0_A, 2, O>;
impl<'a, const O: u8> ADSMS0_W<'a, O> {
    #[doc = "A/D conversion start request signal generated by the GTADTRA register during up-counting."]
    #[inline(always)]
    pub fn _00(self) -> &'a mut W {
        self.variant(ADSMS0_A::_00)
    }
    #[doc = "A/D conversion start request signal generated by the GTADTRA register during down-counting."]
    #[inline(always)]
    pub fn _01(self) -> &'a mut W {
        self.variant(ADSMS0_A::_01)
    }
    #[doc = "A/D conversion start request signal generated by the GTADTRB register during up-counting."]
    #[inline(always)]
    pub fn _10(self) -> &'a mut W {
        self.variant(ADSMS0_A::_10)
    }
    #[doc = "A/D conversion start request signal generated by the GTADTRB register during down-counting."]
    #[inline(always)]
    pub fn _11(self) -> &'a mut W {
        self.variant(ADSMS0_A::_11)
    }
}
#[doc = "Field `ADSMEN0` reader - A/D Conversion Start Request Signal Monitor 0 Output Enabling"]
pub type ADSMEN0_R = crate::BitReader<ADSMEN0_A>;
#[doc = "A/D Conversion Start Request Signal Monitor 0 Output Enabling\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ADSMEN0_A {
    #[doc = "0: Output of A/D conversion start request signal monitor 0 is disabled."]
    _0 = 0,
    #[doc = "1: Output of A/D conversion start request signal monitor 0 is enabled."]
    _1 = 1,
}
impl From<ADSMEN0_A> for bool {
    #[inline(always)]
    fn from(variant: ADSMEN0_A) -> Self {
        variant as u8 != 0
    }
}
impl ADSMEN0_R {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub fn variant(&self) -> ADSMEN0_A {
        match self.bits {
            false => ADSMEN0_A::_0,
            true => ADSMEN0_A::_1,
        }
    }
    #[doc = "Checks if the value of the field is `_0`"]
    #[inline(always)]
    pub fn is_0(&self) -> bool {
        *self == ADSMEN0_A::_0
    }
    #[doc = "Checks if the value of the field is `_1`"]
    #[inline(always)]
    pub fn is_1(&self) -> bool {
        *self == ADSMEN0_A::_1
    }
}
#[doc = "Field `ADSMEN0` writer - A/D Conversion Start Request Signal Monitor 0 Output Enabling"]
pub type ADSMEN0_W<'a, const O: u8> = crate::BitWriter<'a, u32, GTADSMR_SPEC, ADSMEN0_A, O>;
impl<'a, const O: u8> ADSMEN0_W<'a, O> {
    #[doc = "Output of A/D conversion start request signal monitor 0 is disabled."]
    #[inline(always)]
    pub fn _0(self) -> &'a mut W {
        self.variant(ADSMEN0_A::_0)
    }
    #[doc = "Output of A/D conversion start request signal monitor 0 is enabled."]
    #[inline(always)]
    pub fn _1(self) -> &'a mut W {
        self.variant(ADSMEN0_A::_1)
    }
}
#[doc = "Field `ADSMS1` reader - A/D Conversion Start Request Signal Monitor 1 Selection"]
pub type ADSMS1_R = crate::FieldReader<u8, ADSMS1_A>;
#[doc = "A/D Conversion Start Request Signal Monitor 1 Selection\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum ADSMS1_A {
    #[doc = "0: A/D conversion start request signal generated by the GTADTRA register during up-counting."]
    _00 = 0,
    #[doc = "1: A/D conversion start request signal generated by the GTADTRA register during down-counting."]
    _01 = 1,
    #[doc = "2: A/D conversion start request signal generated by the GTADTRB register during up-counting."]
    _10 = 2,
    #[doc = "3: A/D conversion start request signal generated by the GTADTRB register during down-counting."]
    _11 = 3,
}
impl From<ADSMS1_A> for u8 {
    #[inline(always)]
    fn from(variant: ADSMS1_A) -> Self {
        variant as _
    }
}
impl ADSMS1_R {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub fn variant(&self) -> ADSMS1_A {
        match self.bits {
            0 => ADSMS1_A::_00,
            1 => ADSMS1_A::_01,
            2 => ADSMS1_A::_10,
            3 => ADSMS1_A::_11,
            _ => unreachable!(),
        }
    }
    #[doc = "Checks if the value of the field is `_00`"]
    #[inline(always)]
    pub fn is_00(&self) -> bool {
        *self == ADSMS1_A::_00
    }
    #[doc = "Checks if the value of the field is `_01`"]
    #[inline(always)]
    pub fn is_01(&self) -> bool {
        *self == ADSMS1_A::_01
    }
    #[doc = "Checks if the value of the field is `_10`"]
    #[inline(always)]
    pub fn is_10(&self) -> bool {
        *self == ADSMS1_A::_10
    }
    #[doc = "Checks if the value of the field is `_11`"]
    #[inline(always)]
    pub fn is_11(&self) -> bool {
        *self == ADSMS1_A::_11
    }
}
#[doc = "Field `ADSMS1` writer - A/D Conversion Start Request Signal Monitor 1 Selection"]
pub type ADSMS1_W<'a, const O: u8> =
    crate::FieldWriterSafe<'a, u32, GTADSMR_SPEC, u8, ADSMS1_A, 2, O>;
impl<'a, const O: u8> ADSMS1_W<'a, O> {
    #[doc = "A/D conversion start request signal generated by the GTADTRA register during up-counting."]
    #[inline(always)]
    pub fn _00(self) -> &'a mut W {
        self.variant(ADSMS1_A::_00)
    }
    #[doc = "A/D conversion start request signal generated by the GTADTRA register during down-counting."]
    #[inline(always)]
    pub fn _01(self) -> &'a mut W {
        self.variant(ADSMS1_A::_01)
    }
    #[doc = "A/D conversion start request signal generated by the GTADTRB register during up-counting."]
    #[inline(always)]
    pub fn _10(self) -> &'a mut W {
        self.variant(ADSMS1_A::_10)
    }
    #[doc = "A/D conversion start request signal generated by the GTADTRB register during down-counting."]
    #[inline(always)]
    pub fn _11(self) -> &'a mut W {
        self.variant(ADSMS1_A::_11)
    }
}
#[doc = "Field `ADSMEN1` reader - A/D Conversion Start Request Signal Monitor 1 Output Enabling"]
pub type ADSMEN1_R = crate::BitReader<ADSMEN1_A>;
#[doc = "A/D Conversion Start Request Signal Monitor 1 Output Enabling\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ADSMEN1_A {
    #[doc = "0: Output of A/D conversion start request signal monitor 1 is disabled."]
    _0 = 0,
    #[doc = "1: Output of A/D conversion start request signal monitor 1 is enabled."]
    _1 = 1,
}
impl From<ADSMEN1_A> for bool {
    #[inline(always)]
    fn from(variant: ADSMEN1_A) -> Self {
        variant as u8 != 0
    }
}
impl ADSMEN1_R {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub fn variant(&self) -> ADSMEN1_A {
        match self.bits {
            false => ADSMEN1_A::_0,
            true => ADSMEN1_A::_1,
        }
    }
    #[doc = "Checks if the value of the field is `_0`"]
    #[inline(always)]
    pub fn is_0(&self) -> bool {
        *self == ADSMEN1_A::_0
    }
    #[doc = "Checks if the value of the field is `_1`"]
    #[inline(always)]
    pub fn is_1(&self) -> bool {
        *self == ADSMEN1_A::_1
    }
}
#[doc = "Field `ADSMEN1` writer - A/D Conversion Start Request Signal Monitor 1 Output Enabling"]
pub type ADSMEN1_W<'a, const O: u8> = crate::BitWriter<'a, u32, GTADSMR_SPEC, ADSMEN1_A, O>;
impl<'a, const O: u8> ADSMEN1_W<'a, O> {
    #[doc = "Output of A/D conversion start request signal monitor 1 is disabled."]
    #[inline(always)]
    pub fn _0(self) -> &'a mut W {
        self.variant(ADSMEN1_A::_0)
    }
    #[doc = "Output of A/D conversion start request signal monitor 1 is enabled."]
    #[inline(always)]
    pub fn _1(self) -> &'a mut W {
        self.variant(ADSMEN1_A::_1)
    }
}
impl R {
    #[doc = "Bits 0:1 - A/D Conversion Start Request Signal Monitor 0 Selection"]
    #[inline(always)]
    pub fn adsms0(&self) -> ADSMS0_R {
        ADSMS0_R::new((self.bits & 3) as u8)
    }
    #[doc = "Bit 8 - A/D Conversion Start Request Signal Monitor 0 Output Enabling"]
    #[inline(always)]
    pub fn adsmen0(&self) -> ADSMEN0_R {
        ADSMEN0_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bits 16:17 - A/D Conversion Start Request Signal Monitor 1 Selection"]
    #[inline(always)]
    pub fn adsms1(&self) -> ADSMS1_R {
        ADSMS1_R::new(((self.bits >> 16) & 3) as u8)
    }
    #[doc = "Bit 24 - A/D Conversion Start Request Signal Monitor 1 Output Enabling"]
    #[inline(always)]
    pub fn adsmen1(&self) -> ADSMEN1_R {
        ADSMEN1_R::new(((self.bits >> 24) & 1) != 0)
    }
}
impl W {
    #[doc = "Bits 0:1 - A/D Conversion Start Request Signal Monitor 0 Selection"]
    #[inline(always)]
    #[must_use]
    pub fn adsms0(&mut self) -> ADSMS0_W<0> {
        ADSMS0_W::new(self)
    }
    #[doc = "Bit 8 - A/D Conversion Start Request Signal Monitor 0 Output Enabling"]
    #[inline(always)]
    #[must_use]
    pub fn adsmen0(&mut self) -> ADSMEN0_W<8> {
        ADSMEN0_W::new(self)
    }
    #[doc = "Bits 16:17 - A/D Conversion Start Request Signal Monitor 1 Selection"]
    #[inline(always)]
    #[must_use]
    pub fn adsms1(&mut self) -> ADSMS1_W<16> {
        ADSMS1_W::new(self)
    }
    #[doc = "Bit 24 - A/D Conversion Start Request Signal Monitor 1 Output Enabling"]
    #[inline(always)]
    #[must_use]
    pub fn adsmen1(&mut self) -> ADSMEN1_W<24> {
        ADSMEN1_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "General PWM Timer A/D Conversion Start Request Signal Monitoring Register\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [gtadsmr](index.html) module"]
pub struct GTADSMR_SPEC;
impl crate::RegisterSpec for GTADSMR_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [gtadsmr::R](R) reader structure"]
impl crate::Readable for GTADSMR_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [gtadsmr::W](W) writer structure"]
impl crate::Writable for GTADSMR_SPEC {
    type Writer = W;
    const ZERO_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
    const ONE_TO_MODIFY_FIELDS_BITMAP: Self::Ux = 0;
}
#[doc = "`reset()` method sets GTADSMR to value 0"]
impl crate::Resettable for GTADSMR_SPEC {
    const RESET_VALUE: Self::Ux = 0;
}
