
[package]
name = "ra2a1"
version = "0.3.0"
edition = "2024"
description = "Peripheral Access Crate (PAC) for R7FA2A1."
authors = ["Nathan Larsen <n8tlarsen@gmail.com>", "Addison Heavner <addisonheavner@gmail.com>", "Tri Nguyen <trongtribk06@gmail.com>"]
keywords = ["ra2a1", "ra", "arm", "cortex-m", "renesas"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ra-rs/ra"
documentation = "https://docs.rs/crate/ra2a1-pac/latest"
categories = ["embedded", "hardware-support", "no-std"]
readme = "README.md"

[package.metadata.docs.rs]
features = ["all-peripherals", "critical-section", "rt"]

[dependencies]
critical-section = { version = "1.1", optional = true }
cortex-m = "0.7"
cortex-m-rt = { version = "0.7.5", optional = true }
vcell = "0.1.3"
portable-atomic = { version = "1.11.0"}

[features]

rt = ["cortex-m-rt/device"]
critical-section = ["dep:critical-section"]

acmphs0 = []
acmplp = []
adc160 = []
agt0 = []
agt1 = []
bus = []
cac = []
can0 = []
crc = []
ctsu = []
dac12 = []
dac8 = []
dbg = []
doc = []
dtc = []
elc = []
fcache = []
gpt161 = []
gpt162 = []
gpt163 = []
gpt164 = []
gpt165 = []
gpt166 = []
gpt320 = []
gpt_ops = []
icu = []
iic0 = []
iic1 = []
iwdt = []
kint = []
mmf = []
mmpu = []
mstp = []
opamp = []
pfs = []
pmisc = []
poeg = []
port0 = []
port1 = []
port2 = []
port3 = []
port4 = []
port5 = []
port9 = []
rtc = []
sci0 = []
sci1 = []
sci9 = []
sdadc24 = []
smpu = []
spi0 = []
spi1 = []
spmon = []
sram = []
system = []
tsn = []
usbfs = []
wdt = []
all-peripherals = ["acmphs0", "acmplp", "adc160", "agt0", "agt1", "bus", "cac", "can0", "crc", "ctsu", "dac12", "dac8", "dbg", "doc", "dtc", "elc", "fcache", "gpt161", "gpt162", "gpt163", "gpt164", "gpt165", "gpt166", "gpt320", "gpt_ops", "icu", "iic0", "iic1", "iwdt", "kint", "mmf", "mmpu", "mstp", "opamp", "pfs", "pmisc", "poeg", "port0", "port1", "port2", "port3", "port4", "port5", "port9", "rtc", "sci0", "sci1", "sci9", "sdadc24", "smpu", "spi0", "spi1", "spmon", "sram", "system", "tsn", "usbfs", "wdt"]
